name: Push Changes To S3

on:
  workflow_dispatch: 
  
permissions: 
  id-token: write

jobs:
  Push_To_S3:
    runs-on: ubuntu-latest
    
      
    steps:
      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::732555349688:role/CloudResumeChallengeOIDCRole
          aws-region: us-east-2
          disable-retry: true
          
      - name: Grab new website files
        uses: actions/checkout@v4
        with:
          sparse-checkout: | 
            site
      - name: Upload new s3 files
        run: aws s3 cp site s3://maxbeezywebsite/ --recursive --exclude "package.json"
        
      - name: Invalidate Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id E19OV94394U98B --paths "/*"
        
